# Generated by Django 4.2.3 on 2023-07-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Producto1',
        ),
    ]
